config/routes.rb
Rails.application.routes.draw do


  resources :products
  resources :admins, path: "admin"
  resources :users
  resources :sessions
  resources :categories, only: [:index, :show]
  resources :carts

  get '/login'  => 'sessions#new'
  get '/logout'  => 'sessions#destroy'

  get 'checkout' => 'carts#checkout'

  get '/carts/:id' => 'carts#show'
  delete '/carts' => 'carts#delete'

  root 'products#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  belongs_to :user
  has_and_belongs_to_many :products

  enum status: {in_cart: 0, purchased: 1}

  def total_price
    self.products.inject(0){|sum, p| sum + p.price}
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products

  validates_presence_of :name
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :category

  has_and_belongs_to_many :carts

  validates :price, :quantity, numericality: true
  validates :name, :description, :price, :quantity, presence: true

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  has_many :carts

  include BCrypt

  validates_presence_of :email, :name, :password
  validates_uniqueness_of :email

  has_secure_password

  enum role: [:customer, :admin]

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
    if current_user.role == "admin"
      @products = Product.all
    else
      redirect_to products_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def logged_in?
    session[:user_id] != nil
  end

  helper_method :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def current_cart
    @current_cart ||= Cart.find_by(user_id: current_user.id, status: 0) if session[:user_id]
  end

  helper_method :current_cart

  def quantities
    @quantities = Hash.new(0)
    current_cart.products.each do |p|
      @quantities[p.name] += 1
    end
  end

  helper_method :quantities

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  protect_from_forgery :except => [:destroy]

  def index
    @carts = Cart.where(user_id: current_user.id, status: 1)
  end

  def show
    @products = current_cart.products.uniq
    @total_price = current_cart.total_price
    quantities
  end

  def create
  end

  def update
    if request.xhr?
      product = Product.find(params[:product_id])
      product_quantity = params[:quantity].to_i
      quantities
      if product.quantity < product_quantity || (@quantities[product.name] + product_quantity) > product.quantity
        flash[:danger] = "Please enter a quantity less than the stock available"
        redirect_to products
      else
        product_quantity.times do
          current_cart.products << product
        end
        @cart = current_cart
        @products = current_cart.products.uniq
        @total_price = current_cart.total_price
        quantities
        render partial: 'cart', locals: {products: @products, quantities: @quantities, total_price: @total_price}
      end
    else
      p params
      product = Product.find(params[:cart][:item_id])
      product_quantity = params[:name][:quantity].to_i
      quantities
      if product.quantity < product_quantity || (@quantities[product.name] + product_quantity) > product.quantity
        flash[:danger] = "Please enter a quantity less than the stock available"
        redirect_to product
      else
        product_quantity.times do
          current_cart.products << product
        end
        @cart = current_cart
        @products = current_cart.products.uniq
        @total_price = current_cart.total_price
        quantities
        redirect_to cart_path
      end
    end
  end

  def destroy
    product = Product.find(params[:id])
    if request.xhr?
      current_cart.products.delete(product)
      @products = current_cart.products.uniq
      @total_price = current_cart.total_price
      quantities
      render partial: 'cart', locals: {products: @products, quantities: @quantities, total_price: @total_price}
    else
      current_cart.products.delete(product)
      redirect_to current_cart
    end
  end

  def checkout
    @products = current_cart.products.uniq
    @total_price = current_cart.total_price
    quantities
    Product.all.each do |product|
      product.quantity -= @quantities[product.name]
      product.save
    end
    CheckoutMailer.checkout_email(current_user, current_cart).deliver_now
    current_cart.status = 1
    current_cart.save
    Cart.create(user_id: current_user.id)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find params[:id]
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
    @categories = Category.all
    @cart = current_cart
  end

  def show
    @cart = current_cart
    @product = Product.find(params[:id])
  end

  def new
    redirect_to products_path if current_user.role == "customer"
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:success] = "Product was successfully created."
      redirect_to admins_path
    else
      flash[:danger] = @product.errors.full_messages
      redirect_to admins_path
    end
  end

  def edit
    redirect_to products_path if current_user.role == "customer"
  end

  def update
    if @product.update(product_params)
      flash[:success] = "Product was successfully updated."
      redirect_to admins_path
    else
      flash[:danger] = @product.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = "Product was successfully destroyed."
      redirect_to admins_path
    else
      flash[:danger] = "Product failed to destroy."
      redirect_to admins_path
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :quantity)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    puts "LOG LOOKING FOR EMAIL: #{params[:session][:email]} "
    @user = User.find_by email: params[:session][:email]
    if @user
      @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "Login successful."
      if @user.role == "admin"
        redirect_to admins_path
      else
        redirect_to products_path
      end
    else
      flash[:danger] = "Login failed. Invalid email or password."
      redirect_to login_path
    end

  end

  def destroy
    session.clear
    flash[:success] = "Logout successful."
    redirect_to products_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.role = User.roles[:customer]
    if @user.save
      Cart.create(user: @user)
      session[:user_id] = @user.id
      UserMailer.welcome_email(@user).deliver_now
      flash[:success] = "Account was successfully created."
      redirect_to products_path
    else
      flash[:danger] = "Username or password is invalid or already taken, please try again."
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def logged_in?
    session[:user_id] != nil
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/views/admins/index.haml
%div.container
  =link_to 'New Product', new_product_path, {class: "btn btn-primary", id: "new-item-btn"}
  %table.table
    %thead.thead-inverse
      %tr
        %th Product
        %th Price
        %th Quantity
        %th
        %th
        %th

    %tbody
      - @products.each do |product|
        %tr
          %td= product.name
          %td= number_to_currency(product.price)
          %td= product.quantity
          %td= link_to 'Show', product
          %td= link_to 'Edit', edit_product_path(product)
          %td= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

app/views/carts/_cart.haml
%h4.container Shopping Cart
%table.table.container
  %thead.thead-inverse
    %tr
      %th Product
      %th Price
      %th Quantity
      %th
      %th

  %tbody
    - products.each do |product|
      %tr
        %td= product.name
        %td= number_to_currency(product.price)
        %td= quantities[product.name]
        %td{id: product.id.to_s}
          %button.btn.btn-default.btn-sm
            -{id: product.id.to_s}
            Remove


%div
  = 'Total Price: '
  = number_to_currency(total_price)

%br

app/views/carts/checkout.haml
%h2.container Thank you for shopping at Krispy Shoppe
%h4.container Below is a list of your purchases today
%div.container
  %table.table
    %thead.thead-inverse
      %tr
        %th Product
        %th Price
        %th Quantity

    %tbody
      - @products.each do |product|
        %tr
          %td= product.name
          %td= number_to_currency(product.price)
          %td= @quantities[product.name]

%div.container
  = 'Your Order Total: '
  = number_to_currency(@total_price)

app/views/carts/index.haml
%h4.container Order History
%div.container
  %table.table
    %thead.thead-inverse
      %tr
        %th Order Date
        %th Product
        %th Quantity
        %th Price

    %tbody
      - @carts.each do |cart|
        %tr
          %td{colspan:'4'}= cart.updated_at
        - @quantities = Hash.new(0)
        - cart.products.each do |p|
          - @quantities[p.name] += 1
        -cart.products.uniq.each do |product|
          %tr
            %td
            %td= product.name
            %td= @quantities[product.name]
            %td= number_to_currency(product.price)
        %tr
          %td
          %td
          %td
          %td
            = 'Order Total: '
            = number_to_currency(cart.total_price)
        %tr
          %td
          %td
          %td
          %td

app/views/carts/show.haml
%h4.container Shopping Cart
%div.container
  %table.table
    %thead.thead-inverse
      %tr.container
        %th Product
        %th Price
        %th Quantity
        %th

    %tbody
      - @products.each do |product|
        %tr.container
          %td= product.name
          %td= number_to_currency(product.price)
          %td= @quantities[product.name]
          %td= link_to 'Remove', cart_path(product.id), :method => :delete

%div.container
  = 'Total Price: '
  = number_to_currency(@total_price)

%div.container
  = link_to 'Checkout', checkout_url, {class: 'btn btn-success'}

app/views/categories/show.haml
- @category.products.each do |product|
  .col-sm-4.col-lg-4.col-md-4
    .thumbnail
      %img{src: "http://ecx.images-amazon.com/images/I/61Duy2H5s1L._SL1500_.jpg"}
        .caption
          %h4.pull-right
            =number_to_currency(product.price)
          %h4
            =link_to truncate(product.name, length: 24), product

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Krispy Shoppe
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %a.navbar-brand{href: products_path, } Online Shoppe
        .ul.nav.navbar-nav.navbar-right
          -if logged_in?
            .li
              =link_to 'Order History', carts_path, {class: 'btn btn-default'}
              %a{href: "/carts/show", class: 'btn btn-default' } Cart
              =link_to 'Logout', logout_path, {class: 'btn btn-default'}
          -else
            .li
              =link_to 'Login', new_session_path, {class: 'btn btn-default'}
              =link_to 'Sign Up', new_user_path, {class: 'btn btn-default'}

    %br
    %br
    %br
    - flash.each do |message_type, message|
      %div{:class => "alert alert-#{message_type}"}= message
    = yield

app/views/products/_form.haml
.jumbotron.center-block.container
  = form_for @product do |f|
    - if @product.errors.any?
      #error_explanation
        %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
        %ul
          - @product.errors.full_messages.each do |msg|
            %li= msg

    %fieldset.form-group
      =f.label :name
      %div=f.text_field :name
    %fieldset.form-group
      =f.label :description
      %div=f.text_field :description
    %fieldset.form-group
      =f.label :price
      %div=f.text_field :price
    %fieldset.form-group
      =f.label :quantity
      %div=f.text_field :quantity
      = f.submit 'Save', {class: 'btn btn-primary'}

app/views/products/edit.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.haml
%div.col-xs-3
  .list-group.col-sm-12.col-sm-12.col-sm-12
    -@categories.each do |category|
      =link_to category.name, "/categories/#{category.id}", {class: 'list-group-item'}
%div#append_cart.col-xs-9
%div.col-xs-9.pull-right
  - @products.each do |product|
    .col-sm-4.col-lg-4.col-md-4
      .thumbnail
        %img{src: "http://ecx.images-amazon.com/images/I/61Duy2H5s1L._SL1500_.jpg"}
          .caption
            %h5.pull-right
              =number_to_currency(product.price)
            %h5
              =link_to truncate(product.name, length: 24), product
            %h5
              ="Stock: "
              =product.quantity
            - if current_user
              %div.add_cart
                = form_for(@cart) do |f|
                  .field
                    = f.hidden_field :item_id, value: product.id
                  %fieldset.form-group
                    = f.label :quantity
                    = number_field :name, "quantity"
                  - if product.quantity >= 1
                    = f.submit "Add To Cart", {class: "btn btn-success btn-sm"}
                  - else
                    = f.submit "Add To Cart", {class: "btn btn-success btn-sm disabled"}

app/views/products/new.haml
%h1.container New product

= render 'form'

%div.container
  = link_to 'Back', admins_path, {class: 'btn btn-default'}

app/views/products/show.haml
.row-fluid.jumbotron.container
  %p#notice= notice
  .col-sm-8.col-lg-8.col-md-8
    %p.center-block
      %b Name:
      = @product.name
    .thumbnail
      = image_tag('http://ecx.images-amazon.com/images/I/61Duy2H5s1L._SL1500_.jpg')

    %p
      %b Category:
      = @product.category.name
    %p
      %b Description:
      = @product.description
    %p
      %b Quantity:
      = @product.quantity
    %p
      %b Price:
      = number_to_currency(@product.price)
    %p
    - if current_user
      = form_for(@cart) do |f|
        .field
          = f.hidden_field :item_id, value: @product.id
        %fieldset.form-group
          = number_field :name, "quantity"
        - if @product.quantity >= 1
          = f.submit "Add To Cart", {class: "btn btn-success"}
        - else
          = f.submit "Add To Cart", {class: "btn btn-success disabled"}

    = link_to 'Back', products_path, {class: "btn btn-default"}

app/views/users/_form.haml
.jumbotron.center-block.container
  = form_for @user do |f|
    - if @user.errors.any?
      #error_explanation
        %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg

    %fieldset.form-group.col-md-offset-5
      =f.label :name
      %div=f.text_field :name
    %fieldset.form-group.col-md-offset-5
      =f.label :email
      %div=f.text_field :email, {type: 'email'}
    %fieldset.form-group.col-md-offset-5
      =f.label :password
      %div=f.text_field :password, {type: 'password'}
      = f.submit 'Save', {class: 'btn btn-primary'}

app/views/users/new.haml
%h1.container Register

=render 'form'